USE sucos;



CREATE TABLE tabela_de_vendedores (
MATRICULA VARCHAR(5),
NOME VARCHAR(100),
PERCENTUAL_COMISSAO FLOAT);



ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_ADMISSAO DATE);


ALTER TABLE tabela_de_vendedores ADD COLUMN (DE_FERIAS BIT);


ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);



INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00235', 'Márcio Almeida Silva', 0.08, '2014-08-15', 0);

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00236', 'Cláudia Morais', 0.08, '2013-09-17', 1);

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00237', 'Roberta Martins', 0.11, '2017-03-18', 1);

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00238', 'Péricles Alves', 0.11, '2016-08-21', 0);



SELECT NOME, MATRICULA FROM tabela_de_vendedores;

SELECT * FROM TABELA_DE_VENDEDORES WHERE NOME = 'Cláudia Morais';

SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR(DATA_ADMISSAO) >= 2016;

SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR(DATA_ADMISSAO) < 2016 AND DE_FERIAS = 1;